repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: Black Formatter
        language_version: python3
        files: ^backend/|^frontend/
        args: ["--line-length=88"]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Flake8 Linter
        language: python
        entry: flake8
        files: ^backend/|^frontend/
        args: ["--config=.flake8"]
        additional_dependencies: [flake8==6.0.0]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Isort Import Sorter
        language_version: python3
        files: ^backend/|^frontend/
        args: ["--profile", "black"]

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
      - id: autopep8
        name: autopep8 fixer
        language_version: python3
        files: ^backend/|^frontend/
