services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/data_db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
     image: apache/airflow:2.6.2
     environment:
       - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
     volumes:
       - ./scripts:/opt/airflow/dags  # So it can see airflow_ml_pipeline.py
     ports:
       - "8080:8080"
volumes:
  postgres_data:
