"""Add unique constraint to file_name in datasets

Revision ID: b78dfb4a78ba
Revises: fd5e69127c23
Create Date: 2025-01-13 16:50:09.346785

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b78dfb4a78ba"
down_revision: Union[str, None] = "fd5e69127c23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "datasets", ["file_name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "datasets", type_="unique")
    # ### end Alembic commands ###
