name: Data Analysis Platform CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 3) Install Docker Compose
      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" \
            -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # (Optional) Set up Docker Buildx for advanced caching features
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # (Optional) Cache Docker layers to speed up future builds
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Create .env file for backend
        run: |
          cat <<EOF > backend/.env
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          TEST_DATABASE_URL=${{ secrets.TEST_DATABASE_URL }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          ALGORITHM=${{ secrets.ALGORITHM }}
          ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
          BACKEND_CORS_ORIGINS=${{ secrets.BACKEND_CORS_ORIGINS }}
          EOF

      - name: Create .env file for frontend
        run: |
          cat <<EOF > frontend/.env
          BACKEND_URL=${{ secrets.FRONTEND_BACKEND_URL }}
          ML_BACKEND_URL=${{ secrets.FRONTEND_ML_BACKEND_URL }}
          EOF
      - name: Build Docker containers
        run: |
          docker-compose build

      # Start containers in background so we can run tests & lint
      - name: Start Containers
        run: docker-compose up -d db backend-api backend-ml

      - name: Wait for Services
        run: |
          # Simple wait loop for Postgres & the API containers to become healthy
          # (increase attempts/interval if your migrations or startup are slow)
          for i in {1..30}; do
            if docker-compose ps | grep \(healthy\) ; then
              echo "Containers are healthy!"
              break
            fi
            echo "Waiting for containers to be healthy..."
            sleep 5
          done

      - name: Run Tests (backend-api)
        run: |
          # Run the FastAPI tests
          docker-compose exec -T backend-api pytest /app/tests

      - name: Run Tests (backend-ml)
        run: |
          # Run the ML container tests
          docker-compose exec -T backend-ml pytest /app/tests

      - name: Lint with flake8 (backend)
        run: |
          docker-compose exec -T backend-api flake8 .

      - name: Check Streamlit app availability
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl

          # Try to connect to the Streamlit app for up to 60 seconds
          max_attempts=60
          attempt=1
          until curl -s -o /dev/null -w "%{http_code}" http://localhost:8501 | grep 200 || [ $attempt -eq $max_attempts ]; do
            echo "Attempt $attempt failed. Waiting for Streamlit to become available..."
            attempt=$((attempt + 1))
            sleep 1
          done

          if [ $attempt -eq $max_attempts ]; then
            echo "Streamlit app did not become available within the timeout."
            exit 1
          else
            echo "Streamlit app is available!"
          fi
