name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: data_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      VIRTUAL_ENV: venv
      PATH: venv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH
      # These will be updated later with the runner's IP
      DATABASE_URL: ""
      TEST_DATABASE_URL: ""
      pythonLocation: /opt/hostedtoolcache/Python/3.10.16/x64
      LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.16/x64/lib
      PGPASSWORD: password

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Create a Docker network
      - name: Create a Docker network
        run: docker network create my_network

      # 4. Connect the service container to the network
      - name: Connect the service container to the network
        run: docker network connect my_network ${{ job.services.db.id }}

      # 5. Get the Runner's IP Address on the Network
      - name: Get Runner IP
        id: get_runner_ip
        run: |
          RUNNER_IP=$(docker network inspect my_network -f '{{range .Containers}}{{if eq .Name "'$HOSTNAME'"}}{{.IPv4Address}}{{end}}{{end}}' | cut -d '/' -f 1)
          echo "Runner IP: $RUNNER_IP"
          echo "RUNNER_IP=$RUNNER_IP" >> $GITHUB_ENV

      # 6. Update DATABASE_URLs with Runner IP
      - name: Update DATABASE_URLs
        run: |
          echo "DATABASE_URL=postgresql://postgres:password@$RUNNER_IP:5432/data_db" >> $GITHUB_ENV
          echo "TEST_DATABASE_URL=postgresql://postgres:password@$RUNNER_IP:5432/data_db_test" >> $GITHUB_ENV

      # 7. List Docker containers (debugging)
      - name: List Docker Containers
        run: docker ps -a

      # 8. Test DB host resolution (This will likely still fail, but that's okay)
      - name: Test DB host resolution
        run: |
          getent hosts db || echo "db not resolvable"

      # 9. Ping db (This will also likely fail, using IP is better)
      - name: Ping db
        run: |
          ping -c 4 db || echo "db not reachable"

      # 10. Display /etc/hosts (optional)
      - name: Display /etc/hosts
        run: cat /etc/hosts

      # 11. Get PostgreSQL Logs
      - name: Get PostgreSQL Logs
        run: |
          docker logs $(docker ps -q --filter "ancestor=postgres:13") || echo "No logs available"

      # 12. Wait for PostgreSQL to be ready (Use IP for nc)
      - name: Wait for PostgreSQL
        run: |
          for i in {1..20}; do
            nc -z -v -w 1 $RUNNER_IP 5432 && echo "PostgreSQL is up!" && break || echo "db:5432 - no response"
            if [[ $i == 20 ]]; then
              echo "PostgreSQL did not start within the expected time."
              exit 1
            fi
            echo "Waiting for PostgreSQL..."
            sleep 5
          done

      # 13. Check PostgreSQL Status (Use IP for psql)
      - name: Check PostgreSQL Status
        run: |
          psql -h $RUNNER_IP -p 5432 -U postgres -c "\l"
        env:
          PGPASSWORD: password

      # 14. Create Test Database (Use IP for psql)
      - name: Create Test Database
        run: |
          psql -h $RUNNER_IP -p 5432 -U postgres -c "CREATE DATABASE data_db_test;"
        env:
          PGPASSWORD: password

      # 15. Verify data_db_test exists (Use IP for psql)
      - name: Verify data_db_test exists
        run: |
          psql -h $RUNNER_IP -p 5432 -U postgres -d data_db_test -c "\dt"
        env:
          PGPASSWORD: password

      # 16. Install Dependencies
      - name: Install Dependencies
        run: |
          python -m venv venv
          pip install --upgrade pip
          pip install pre-commit
          pip install -r backend/requirements.txt
          pip install pytest pytest-cov

      # 17. Install and Run Pre-Commit Hooks
      - name: Install Pre-Commit Hooks
        run: |
          pre-commit install
          pre-commit run --all-files

      # 18. Apply Migrations to Test Database
      - name: Apply Migrations
        run: |
          alembic upgrade head
        env:
          DATABASE_URL: ${{ env.TEST_DATABASE_URL }}
        working-directory: ./backend

      # 19. Cache pip dependencies to speed up builds
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: |
            venv/lib/python3.10/site-packages
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 20. Run Tests with pytest
      - name: Run Tests
        run: |
          pytest --cov=backend/app --cov-report=xml
        env:
          DATABASE_URL: ${{ env.TEST_DATABASE_URL }}

      # 21. Upload coverage report
      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
