name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: data_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      VIRTUAL_ENV: venv
      PATH: venv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH
      DATABASE_URL: postgresql://postgres:password@db:5432/data_db
      TEST_DATABASE_URL: postgresql://postgres:password@db:5432/data_db_test
      PGPASSWORD: password
      PYTHONPATH: ./backend
      #      pythonLocation: /opt/hostedtoolcache/Python/3.10.16/x64
      #      LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.16/x64/lib

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. List Docker containers (debugging)
      - name: List Docker Containers
        run: docker ps -a

      # 4. Test DB host resolution
      - name: Test DB host resolution
        run: |
          getent hosts db || echo "db not resolvable"

      - name: Debug Python Path
        run: |
          echo "PYTHONPATH: $PYTHONPATH"
          python -c "import sys; print(sys.path)"

      # 5. Ping db (optional)
      - name: Ping db
        run: |
          ping -c 4 db || echo "db not reachable"

      # 6. Display /etc/hosts (optional)
      - name: Display /etc/hosts
        run: cat /etc/hosts

#      # 7. Check User Permissions
#      - name: Check User Permissions
#        run: |
#          psql -h db -p 5432 -U postgres -c "\du"
#        env:
#          PGPASSWORD: password

      # 8. Get PostgreSQL Logs
      - name: Get PostgreSQL Logs
        run: |
          docker logs $(docker ps -q --filter "ancestor=postgres:13") || echo "No logs available"

      # 9. Wait for PostgreSQL to be ready
      - name: Wait for PostgreSQL
        run: |
          for i in {1..20}; do
            pg_isready -h db -p 5432 -U postgres && break
            echo "Waiting for PostgreSQL..."
            sleep 5
          done

      # 10. Check PostgreSQL Status
      - name: Check PostgreSQL Status
        run: |
          psql -h db -p 5432 -U postgres -c "\l"
        env:
          PGPASSWORD: password

      # 11. Create Test Database
      - name: Create Test Database
        run: |
          psql -h db -p 5432 -U postgres -c "CREATE DATABASE data_db_test;"
        env:
          PGPASSWORD: password

      # 12. Verify data_db_test exists
      - name: Verify data_db_test exists
        run: |
          psql -h db -p 5432 -U postgres -d data_db_test -c "\dt"
        env:
          PGPASSWORD: password

      # 13. Install Dependencies
      - name: Install Dependencies
        run: |
          python -m venv venv
          pip install --upgrade pip
          pip install pre-commit
          pip install -r backend/requirements.txt
          pip install pytest pytest-cov

      # 14. Install and Run Pre-Commit Hooks
      - name: Install Pre-Commit Hooks
        run: |
          pre-commit install
          pre-commit run --all-files

      # 15. Apply Migrations to Test Database
      - name: Apply Migrations
        run: |
          alembic upgrade head
        env:
          DATABASE_URL: ${{ env.TEST_DATABASE_URL }}
        working-directory: ./backend

      # 16. Cache pip dependencies to speed up builds
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: |
            venv/lib/python3.10/site-packages
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 17. Run Tests with pytest
      - name: Run Tests
        run: |
          pytest --cov=backend/app --cov-report=xml
        env:
          DATABASE_URL: ${{ env.TEST_DATABASE_URL }}

      # 18. Upload coverage report
      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
