name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: data_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Lint with flake8
      run: |
        source venv/bin/activate
        pip install flake8
        flake8 backend/app/

    - name: Format with black
      run: |
        source venv/bin/activate
        pip install black
        black --check backend/app/

    - name: Run tests
      env:
        DATABASE_URL: postgresql://postgres:password@localhost:5432/data_db
      run: |
        source venv/bin/activate
        cd backend
        alembic upgrade head
        pytest
